language: python

# run on Travis container-based infrastructure
sudo: false

git:
  depth: 99999  # needs all commits to fetch all tags, could not find better solution

addons:
  postgresql: "9.4"

install:
  - pip install psycopg2 --quiet
  - pip install pyyaml --quiet

before_script: 
  - printf "[qwat_test]\nhost=localhost\ndbname=qwat_test\nuser=postgres\n\n[qwat_test_conform]\nhost=localhost\ndbname=qwat_test_conform\nuser=postgres\n\n[qwat_demo]\nhost=localhost\ndbname=qwat_demo\nuser=postgres\n\n" > ~/.pg_service.conf
  - psql -c 'CREATE DATABASE qwat_test;' -U postgres

script: 
  - $TRAVIS_BUILD_DIR/init_qwat.sh -p qwat_test -s 21781 -r
  - $TRAVIS_BUILD_DIR/tests/tests.sh --no-init
  - $TRAVIS_BUILD_DIR/update/verify_upgrade_db.sh

env:
  global:
    - secure: "NtPlzMsTX+P2zOU88R3lGzm7tV/oN+7Zk9rqWp5HonozCmmE1YCKiGb92MXe+C0vW2wcWHWxA/L8r4u4PgwDAAhpNPe27PVBoW8UvbJcDAvKW5kO0gUTYMhGn+nchL3B/UH5sEhQb4RwIjmKrO6fGVL+irMuQFS55/BEgp1nXBo="
