language: python

# run on Travis container-based infrastructure
sudo: false

addons:
  postgresql: "9.4"
  
install:
  - pip install psycopg2 --quiet
  - pip install pyyaml --quiet

before_script: 
  - printf "[qwat]\nhost=localhost\ndbname=qwat\nuser=postgres" > ~/.pg_service.conf
  - psql -c 'CREATE DATABASE qwat;' -U postgres
  
script: $TRAVIS_BUILD_DIR/init_qwat.sh -p qwat -s 21781 -r
