language: python

# run on Travis container-based infrastructure
sudo: false

git:
  depth: 99999  # needs all commits to fetch all tags, could not find better solution

addons:
  postgresql: "9.4"

install:
  - pip install psycopg2 --quiet
  - pip install pyyaml --quiet

before_script: 
  - printf "[qwat_test]\nhost=localhost\ndbname=qwat_test\nuser=postgres\n\n[qwat_test_conform]\nhost=localhost\ndbname=qwat_test_conform\nuser=postgres\n\n[qwat_demo]\nhost=localhost\ndbname=qwat_demo\nuser=postgres\n\n" > ~/.pg_service.conf
  - psql -c 'CREATE DATABASE qwat_test;' -U postgres

script: 
  - $TRAVIS_BUILD_DIR/init_qwat.sh -p qwat_test -s 21781 -r
  - $TRAVIS_BUILD_DIR/tests/tests.sh --no-init
  - $TRAVIS_BUILD_DIR/update/verify_upgrade_db.sh

env:
  global:
    - secure: "roWsFPDmJx30mnO6moZXGcx7HQQcS5HxLz+++AdCZh7B9aOAXcX0eOj6m7b4wl/tkOUgbd1ddYOTRsrVwq3Bbcr5Mt8C37JQMmrSxG1uFC0nVh+K0Z0j2mumlOC5vUdJMOnlMMF+cKlPdh+vG4Izf0X2Rsj4vJdcNeaiQduNT1hyGjL/QaAxaxMyWEhcOzb1H7B/agk8LVnDS5cmfcs4SsVKMbYDxQKzJdDUZunE2IaXIsqPLz7iGE9RV7O476vIGI9GJB1C1VP52h3TT5Ev/xKHY13MFhtindxpS+XdzG4vI39SgdVBjcj2bhpug4ELM2X0Y0MZ5UA00wvUXmfR8bqpQj/675R2fBBc0wI5GJ6WtfxT3mjzv3n1RwGrQ9ByEZJ5TNVvC7c2JIPKs9IAi67esF26GJBkBakb989RBiZMOyr+kGH84q1H75FEAzdyhtLZnLGzIKo9a9wReYiXygZHpA3/TbIwkGgrH89J0G+3wAD4WaeuwoI9s7ZwIIGMuymNX5PUMnOUigS4E6sht7PgJSN0OLlPN8LatsgumOiPKg4Rnjry5rzr/PtHGOsUeJwj6Nu/JpVSqQmICr6u8lHSV5KMZ8aR43MlozMEwwyHeC2SEa0kIaNh90V+1ug6cV5y2caJnvvLBGThX2zQZCwurMDl+rDSRvrTV71H5A4="
